meta:
  schema_version: 4
global:
  no_strict_host_key_checking: true
  vars:
    prefix: '[gobble]'
    msg: Global Gobble!
rig_hosts:
  remote_ssh:
    - ssh:
        address: localhost
        user: mkaplan
        keyPath: ~/.ssh/id_ed25519
  remote_openssh:
    - openssh:
        address: localhost
        user: mkaplan
        keyPath: ~/.ssh/id_ed25519
  local_local:
    - local: true

hosts_aliases:
  all:
    - remote_ssh
    - remote_openssh
    - local_local

plays:
  - name: touch file
    hosts: [all]
    sudo: false
    tags: [setup]
    tasks:
      - name: touch file
        command:
          cmd: echo "Simulated stdout message" >&1 && echo "Simulated stderr message" >&2  && exit 1
